### ISSUE TITLE
Use Chartjs-Plugin-datalabels with vue-chartjs

### ISSUE THREAD

**Issue by HenriSup** [chartjs/chartjs-plugin-datalabels#10]
Hi, i am actually trying to add this plugin to a vue.js project using vue-chartjs and i have no idea how to do it. I installed chartjs-plugin-datalabels using node but then what should i do?

**Comment by simonbrunel** [comment]
I'm not familiar with Vue.js or vue-chartjs, did [that thread](/apertureless/vue-chartjs/issues/94) help?

You will probably need `vue-chartjs 2.8.7` (since this plugin requires `Chart.js 2.7`) and thus `Vue.js 2.4.4`. Then I'm not sure what is the best way to import JavaScript libraries in Vue.js, maybe simply load it via a `<script>` tag (so no need of the node.js package) ([example](https://codepen.io/anon/pen/eeOYeG)):

```html
<!-- index.html -->
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@0.1.0"></script>
```

It may be better to ask this question on the [vue-chartjs](/apertureless/vue-chartjs) project and link to that ticket.

**Comment by simonbrunel** [comment]
@HenriSup did you progress on that integration?

**Comment by HenriSup** [comment]
Yes sorry for the silence it was actually pretty simple just installed it via npm and imported it the way you import component in vue.js and it was on all my charts, just had to add some parameters via the data.plugin.etc.... but I'm not at work this week I'm only telling this by memory. Should I close the topic or would it be better if I add more precision and a clear way to explain how I did when I'll be back at my workplace?

**Comment by simonbrunel** [comment]
Sounds great! It's a good idea to document more precisely the way you get it working, that could help other Vue.js users who want to use this plugin.

**Comment by HenriSup** [comment]
Ok, sorry for the wait i finally managed to get some time to explain how i did it (it's actually pretty simple)
-Install chartJsPluginDataLabels via npm:

`npm install chartjs-plugin-datalabels --save`

-import it as a component in your vue: 

```javascript
import ChartJsPluginDataLabels from 'chartjs-plugin-datalabels';

var app = new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue!'
  },
  components: {
    ChartJsPluginDataLabels,
  },
})
```
and there it is, you should have datalabels on your vue-chartjs :)
if you want to change any options on your charts it's just like the regular chartjs : https://chartjs-plugin-datalabels.netlify.com/options.html

**Comment by simonbrunel** [comment]
Thanks @HenriSup for the follow up!

**Comment by folmert** [comment]
I've added it to `components` property of my single file component, but it got applied to all my components, how can I define a scope for this?
