### ISSUE TITLE
context.dataset.backgroundColor returns Setter & Getter instead of the actual Array

### ISSUE THREAD

**Issue by handhikadj** [chartjs/chartjs-plugin-datalabels#102]
By the way, this is the reproduction: https://codepen.io/dhika345/pen/aPbwvb

As you can see, when I console.log(context.dataset) I've got setter and getter on the backgroundColor object. It should be array. so when I `return context.dataset.backgroundColor`, the color applied instead of such monotone color

Thank you

### Environment:

NPM v5.6.0
Vue.js v 2.5.18
Chart.js v2.7.3
chartjs-plugin-datalabels v0.4.0

**Comment by simonbrunel** [comment]
@handhikadj with `console.log(context.dataset)` you see Vue.js getters/setters because your state is reactive (Vuex) but it works as expected when I run your codepen, `backgroundColor` is a string like `rgba(154,142,180,0.1)`. I guess the monotone color comes from the color alpha (0.1). When I look at your data (https://api.myjson.com/bins/15v6fy), `backgroundColor` is not an array:

![capture](https://user-images.githubusercontent.com/3874900/49700721-d8022500-fbe2-11e8-8106-9f190a56f66d.jpg)
