### ISSUE TITLE
After updating from 0.4.0 to 0.5.0 bug appears [Cannot read property 'positioner' of null]

### ISSUE THREAD

**Issue by poradz** [chartjs/chartjs-plugin-datalabels#104]
On 0.4.0 everything was ok
![image](https://user-images.githubusercontent.com/31520119/49855102-79a89280-fdec-11e8-9870-ff8ee509b0b0.png)

**Comment by simonbrunel** [comment]
@poradz can you please share a jsfiddle that reproduces your issue or point me on the page that throws this exception?

**Comment by simonbrunel** [comment]
Your project [accesses private members](/YetiForceCompany/YetiForceCRM/blob/developer/public_html/layouts/basic/modules/Vtiger/resources/dashboards/Widget.js#L230) but lot of these internals have been changed/refactored since 0.4.0 (I added an explicit [note about it](https://chartjs-plugin-datalabels.netlify.com/guide/)). In your code, [you are setting `_model = null`](/YetiForceCompany/YetiForceCRM/blob/developer/public_html/layouts/basic/modules/Vtiger/resources/dashboards/Widget.js#L247) (private) during the drawing process, however this new version now assumes that the visible state of a label can not change during drawing but only during updates, so I guess that's why you get this exception.

**Comment by simonbrunel** [comment]
I think you could replace the whole `hide*BarDatalabelsIfNeeded` logic by the new [`display: 'auto'` option](https://chartjs-plugin-datalabels.netlify.com/guide/positioning.html#visibility) which hides labels when they overlap, though, it's not exactly the same as what you are currently doing (i.e. hiding labels if it doesn't fit within the bar width).

**Comment by simonbrunel** [comment]
@poradz any update or test case if my previous assumptions was incorrect?

**Comment by simonbrunel** [comment]
@poradz feel free to reopen with more details if this issue is not related to your code accessing internals.

**Comment by poradz** [comment]
Thanks for your help, we'll check your suggestion soon and let you know if it helped.

**Comment by poradz** [comment]
@simonbrunel your assumptions were correct. To maintain our logic and to correct the bug I've changed

`dataItem.$datalabels._model = null;`

to

`dataItem.$datalabels._model.positioner = () => {
									return false;
								}`

https://github.com/YetiForceCompany/YetiForceCRM/pull/9496

Are there better ways to hide labels programmatically?

**Comment by simonbrunel** [comment]
I think `dataItem.$datalabels._model.display = false` is better but still a private API, so I would not expect it to be stable, neither backward compatible. Did you try the new `display: 'auto'` option?

**Comment by poradz** [comment]
I had tried `dataItem.$datalabels._model.display = false` but it didn't work. I had also tried the new `display: 'auto'` option, but for now we prefer hiding labels if it doesn't fit within the bar width.

**Comment by simonbrunel** [comment]
Maybe [`_model.opacity: 0`](/chartjs/chartjs-plugin-datalabels/blob/master/src/label.js#L276) then, but still not ideal. I will need to think about a public API to allow these kind of use cases.
