### ISSUE TITLE
TypeScript types

### ISSUE THREAD

**Issue by LeoTindall** [chartjs/chartjs-plugin-datalabels#11]
Currently, I have issues using this library with my typescript project; could you include a TypeScript types definition file?

Many thanks.

**Comment by simonbrunel** [comment]
@LeoTindall I don't use TypeScript (and not familiar with it), what are your issues? what do you need exactly?

**Comment by LeoTindall** [comment]
The problem is that the TypeScript type checker complains when I try to configure the library. I'm happy to submit a PR with the d.ts file, I was just wondering if you'd be willing to accept it.

**Comment by bitflower** [comment]
@LeoTindall are you planning on adding this to the Chart.js typings or a seperate file for the plugin?

**Comment by simonbrunel** [comment]
@LeoTindall sorry for the late reply: I'm not against the TypeScript definition in this repository (as long as it respects the ESLint code style), however since this plugin is not written using TypeScript, this file will likely not be maintained.

Wouldn't be easier to simply update the Chart.js TypeScript and allow any type for `options.plugins.*` (and `Chart.defaults.global.plugins.*`), which should make your checker happy? This will also be compatible with other plugins.

**Comment by LeoTindall** [comment]
Not a bad idea! I'll make a PR against their repo, thanks.

**Comment by simonbrunel** [comment]
@LeoTindall sounds good, can you please link that ticket to your PR when ready?

**Comment by LiamDotPro** [comment]
@LeoTindall How do I integrate this into my existing typescript project? It throws errors saying it can't find the definition for various files.
