### ISSUE TITLE
Plugin wont work after compress the file with Uglify

### ISSUE THREAD

**Issue by benjaminfunk** [chartjs/chartjs-plugin-datalabels#117]
The problem is not the "mangle" options from uglify. Its the compress. Dont know which type of compress.. still investigating

**Comment by benjaminfunk** [comment]
Test case is hard because the code doesnt throw an error. But i found the part in uglify where the problems happens.

The problem is the options "compress collapse_vars" | https://github.com/mishoo/UglifyJS2#compress-options. If i turn of collapse_vars the datalabels works fine.

But it could be a bug in uglify itself | https://github.com/mishoo/UglifyJS2/issues/3247

**Comment by simonbrunel** [comment]
We switched to Terser (a4924e628f05d) because of a similar issue with Uglify introduced in version 3.4.9. At that time, I investigated what's wrong with our code but can't find any issue (maybe I missed it). You may experience the same problem, in which case you can either pinned you Uglify version to 3.4.8, or disable `collapse_vars` or switch to Terser (or whatever else) since Uglify doesn't seem maintained anymore.

Anyway, we are not considering to "adapt" our code to a bug in a minifier we are not using (and unmaintained). Feel free to reopen if you figure out that the issue is finally in our code.
