### ISSUE TITLE
Display multiple labels for one value

### ISSUE THREAD

**Issue by redoper1** [chartjs/chartjs-plugin-datalabels#145]
Hello,
it would be really nice and useful to have option to display multiple labels for one value of the graph, so we would be able to create graphs like that one on the picture (first line is data value, second is label for this data).

![Image of graph](https://files.davidrychly.cz/multilabel_graph.png)

Possible solution to set the settings was already proposed here: [https://github.com/chartjs/chartjs-plugin-datalabels/issues/63#issuecomment-399784292](https://github.com/chartjs/chartjs-plugin-datalabels/issues/63#issuecomment-399784292)

**Comment by omarsedki** [comment]
I think it will be good feature .it will help with the use of icon fonts  in creating more rich chart like this one.  
![cycle-chart-infographic-template-with-5-parts-vector-19025390](https://user-images.githubusercontent.com/8490104/62600272-23e2a680-b8f7-11e9-86bf-71b76a5e2bfe.jpg)

**Comment by redoper1** [comment]
It starting to look like this plugin is abandoned when there is not any response from the authors for two weeks.

**Comment by simonbrunel** [comment]
Closing in favor of #63 which I feel is the same feature (if not, please explain the difference).

@redoper1 I would not say that this plugin is "abandoned" but rather not in "active" development. I'm still maintaining it by fixing bugs but I'm currently really busy with other (professional) projects and don't have time to implement "feature" requests.

@omarsedki indeed, that's a very good example. It would also help to display labels with different fonts / color (instead of trying to parse rich formatted text which would certainly be a nightmare to implement properly)
