### ISSUE TITLE
Scriptable context options aligned with Chart.js

### ISSUE THREAD

**Issue by stockiNail** [chartjs/chartjs-plugin-datalabels#155]
In new Chart.Js version 2.9.x, there is a similar implementation of context.

In DataLabels there is:

active | bool | Whether the associated element is hovered
-- | -- | --

In [Chart.js](https://www.chartjs.org/docs/latest/general/options.html#option-context) there is:

hover: `true `if hovered

What do you think to be aligned with Chart.JS, renaming it in `hover` ?

**Comment by simonbrunel** [comment]
Hi @stockiNail. 

The `active` context property for this plugin exists for almost two years (c9cab4999533a6d2e1fa8b38806794ac896ad00e) while `hover` in Chart.js exists for about [one week](https://github.com/chartjs/Chart.js/pull/6527) so it doesn't really make sense to consider modifying this plugin since the impact on users would be too important (compared to modifying Chart.js). I also don't want to add both properties.

I chose `active` instead of `hover(ed)` because an element can be active while the mouse is not over the element (for example when `hover.intersect: false, axis: 'y'`). Maybe I don't understand correctly the term "hover" in that case so what does `context.hover` mean in English?!

Note that the [Chart.js docs](https://www.chartjs.org/docs/latest/general/interactions/events.html#events) for `onHover` states: *"Called in the context of the chart and passed the event and an array of **active** elements*.  So I would suggest to align Chart.js instead and rename the `hover` context property to `active`.

**Comment by stockiNail** [comment]
@simonbrunel Thank you very much for your explanation. 

I fully agree with you.
I assumed (wrongly) that scriptable options in CHART.js was taken from Datalabels plugin because they are very similar. And I was surprised to see the differences on the context.
I'm gonna raise the topic to Chart.js asa I can.
