### ISSUE TITLE
textAlignment of datalabels  

### ISSUE THREAD

**Issue by afouad1511** [chartjs/chartjs-plugin-datalabels#161]
this snippet is part of an angular component to render horizontal bar chart and custom data labels above the bars, but the labels changed according the locals, so i want to change the alignment from left-to-right to right-to-left in Arabic locale, but it doesn't work.

```js
offset: function(context) {
  if (context.dataIndex < globalThis.debitsLabelsList.length) {
    context.textAlign = "right"
    var value = context.dataset.data[context.dataIndex];
    if (globalThis.lang == "en") {
      return value > 0 ? 0 : -115;
    } else {
      return value > 0 ? 130 : -15;
    }
  } else {
    context.textAlign = "left"
    var value = context.dataset.data[context.dataIndex];
    if (globalThis.lang == "en") {
      return value > 0 ? 0 : -100;
    } else {
      return value > 0 ? 70 : -15;
    }
  }
}
```

**Comment by simonbrunel** [comment]
Hi @afouad1511! Sorry for the late reply, did you figure out how to implement this use case?

I'm not sure to understand clearly what you are trying to achieve but `context.textAlign` can't work. If you want to change the text alignment dynamically, you need to script that option:

```js
textAlign: (ctx) => ctx.dataIndex < globalThis.debitsLabelsList.length ? 'right' : 'left'
```

Maybe you can use `align` and/or `anchor` instead of `offset` to implement rtl and ltr alignment:

```js
align: (ctx) => globalThis.lang === 'en' ? 'end', 'start',
anchor: (ctx) => globalThis.lang === 'en' ? 'start', 'end'
```

I'm closing this issue but feel free to re-open this ticket with a codepen that reproduces your use case and a screenshot of what you are expecting.
