### ISSUE TITLE
TypeScript error when color callback returns dataset backgroundColor

### ISSUE THREAD

**Issue by JohnArcher** [chartjs/chartjs-plugin-datalabels#169]
For pie charts I am coloring the labels with the same color as the color of the pie pieces. Here is a screenshot:
![image](https://user-images.githubusercontent.com/990724/74230358-8496d580-4cc4-11ea-87cc-9cfd8e2e0788.png)

I achieve this setting the color with the dataset background color:
```javascript
plugins.datalabels = {
    color: function (context) {
        return context.dataset.backgroundColor;
    }
}
```

This works nice at runtime, but the TypeScript compiler complains of not assignable types:
```
error TS2322: Type '(context: Context) => string | CanvasGradient | CanvasPattern | string[] | Scriptable<ChartColor> | ChartColor[]' is not assignable to type 'string | CanvasGradient | CanvasPattern | string[] | ChartColor[] | ((context: Context) => ChartColor)'.
  Type '(context: Context) => string | CanvasGradient | CanvasPattern | string[] | Scriptable<ChartColor> | ChartColor[]' is not assignable to type '(context: Context) => ChartColor'.
    Type 'string | CanvasGradient | CanvasPattern | string[] | Scriptable<ChartColor> | ChartColor[]' is not assignable to type 'ChartColor'.
      Type 'Scriptable<ChartColor>' is not assignable to type 'ChartColor'.
        Type 'Scriptable<ChartColor>' is missing the following properties from type 'string[]': pop, push, concat, join, and 24 more.
```

The type of `context.dataset.backgroundColor` is `ChartColor | ChartColor[] | Scriptable<ChartColor>` (defined in the `@types/chart.js` npm package). 
I tried to extend the datalabels option (in `options.d.ts`) definition of color like so:
```
color?: Indexable<Color> | Scriptable<Color> | ChartColor | ChartColor[] | Scriptable<ChartColor>,
```

But this has no effect, and I am not even sure whether that is the right step to do.

Does anyone know how the definition has to be changed to TypeScript compiler does not complain anymore?

Thanks in advance!

**Comment by simonbrunel** [comment]
Hi @JohnArcher! I think it's because both `Color` and `ChartColor` doesn't alias the exact same types:

In Chart.js:
```js
type ChartColor = string | CanvasGradient | CanvasPattern | string[];
```

In this plugin:
```js
type Color = string | CanvasGradient | CanvasPattern;
```

To me, the Chart.js one is wrong because `string[]` is already supported when used as:

```
backgroundColor?: ChartColor | ChartColor[] | Scriptable<ChartColor>;
```

I would recommend you to open a PR on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) that get rid of `string[]` for `ChartColor`.

**Comment by simonbrunel** [comment]
I'm going to close this issue since the bug is in the Chart.js TS definitions hosted in the DefinitelyTyped repo. We don't maintain the code there so feel free (or anyone else) to submit a PR for it. `ChartColor` shouldn't include `string[]` (as it's implemented in the [Chart.js v3 types](https://github.com/chartjs/Chart.js/blob/master/types/index.esm.d.ts#L1335)):

```ts
export type Color = string | CanvasGradient | CanvasPattern;
```
