### ISSUE TITLE
Any way to return HTML in formatter?

### ISSUE THREAD

**Issue by ccoplestone** [chartjs/chartjs-plugin-datalabels#192]
Hello there,

I'm attempting to style the decimal values smaller than the other numbers like so:

![image](https://user-images.githubusercontent.com/33654282/88824266-0d93c180-d1be-11ea-932c-297d28617353.png)

But I can see that the formatter only accepts text as its format, what I'd like to do is something like so:

```
datalabels: {
    formatter: function(value, context) {
        const formattedValue = Intl.NumberFormat('en-GB', 
            { 
                style: 'currency',
                currency: 'GBP',
                minimumFractionDigits: 0,
                maximumFractionDigits: 0,
            })
            .format(value);
            const decimals = '.00'
        return `${formattedValue} <span style="color:red">${decimals}</span>`
    },
}
```

But it obviously outputs it as all text.

Is there a way around this?

Thanks.

**Comment by himvins** [comment]
Is there any plan for building this feature?

**Comment by simonbrunel** [comment]
@ccoplestone I understand your needs but it's currently not possible.

There is no plan to support HTML because Chart.js is built on top of the `<canvas>` element **which doesn't support rendering HTML**. Obviously, trying to implement an HTML renderer ourselves is not an option and relying on a 3rd party library would bring too much extra code into this project for a very few use cases (and would probably make this plugin dependent of a DOM/HTML environment, which is currently not required).

We could try to introduce and parse a limited set of custom tags (e.g. `<b>, <color>, <size>, etc.`), but it's still not trivial and I think beyond the scope of this lib.

**Comment by krzywiecki** [comment]
@simonbrunel would that be possible to implement maybe `<b>` tag? Or perhaps we could support a limited markdown? I really need to make part of the label bold and would be glad to contribute if you give me a little instruction on how to do so.
