### ISSUE TITLE
Increase in labels decreasing the size of chart

### ISSUE THREAD

**Issue by vishalbiradar** [chartjs/chartjs-plugin-datalabels#228]
I am using chartjs in my angular application.
I have two pie charts, out of one pie chart is having 10 labels whereas the other is having only two.
SO when we look at the charts the actual pie charts are not of same size.
Is there any way we can handle it.

Please refer below screenshot:

<img width="1442" alt="Screenshot 2021-03-10 at 6 45 02 PM" src="https://user-images.githubusercontent.com/29951629/110635111-bed8ec00-81d0-11eb-9f82-59ad6212bf77.png">

**Comment by LeeLenaleee** [comment]
This is because of how chart.js draws the labels. This happens by default on the canvas so when there are lots of labels it needs space so it has to make the chart smaller. If you always want the same size chart you will have to use the HTML legend. (https://www.chartjs.org/docs/latest/configuration/legend.html#html-legends)

**Comment by simonbrunel** [comment]
I'm closing this issue because legend labels are not handled by this plugin but by the [core library](https://github.com/chartjs/Chart.js). 

Please don't create an issue for asking questions, instead use StackOverflow of the [GH discussions](https://github.com/chartjs/Chart.js/discussions).
