### ISSUE TITLE
[next] esm build not in dist

### ISSUE THREAD

**Issue by hsablonniere** [chartjs/chartjs-plugin-datalabels#246]
Hi team,

I'm migrating from chart.js v2 to v3 and I'm looking forward to have good ESM and treeshaking support.
I've been using this plugin so I tried the `2.0.0-rc`.

It works but my the ESM file referenced in the [package.json](https://github.com/chartjs/chartjs-plugin-datalabels/blob/next/package.json#L8) is not in my `node_modules` after installation.

This means my rollup configuration:
* picks up the default CJS file in dist
* which does a `require('chart.js')`
* which imports the whole lib
* and thus prevents treeshaking

I may be mistaken but I think the rollup config is in conflict here: https://github.com/chartjs/chartjs-plugin-datalabels/blob/next/rollup.config.js#L48

How can I help?

**Comment by hsablonniere** [comment]
I just cloned the project, I can prepare a PR if you want ;-)

![Capture d’écran_2021-05-20_15-28-30](https://user-images.githubusercontent.com/236342/118986932-11c4e180-b980-11eb-86c8-063d9b43597b.png)

**Comment by hsablonniere** [comment]
The build correctly generates the esm file.

**Comment by hsablonniere** [comment]
It's weird because the package.json is OK and the `npm pack --dry-run` has the ESM file.

![Capture d’écran_2021-05-20_15-33-15](https://user-images.githubusercontent.com/236342/118987608-b6dfba00-b980-11eb-85f5-591871e638c0.png)

**Comment by hsablonniere** [comment]
@simonbrunel Ah ok. I looked at some scripts but not those...

Thanks for your work and the plugin in general ;-)

We use it in our components library: https://www.clever-cloud.com/doc/clever-components/?path=/story/%F0%9F%9B%A0-overview-cc-tile-requests--default-story

**Comment by hsablonniere** [comment]
Do you want a PR?

**Comment by simonbrunel** [comment]
This is fixed by 0870ebe, released in [v2.0.0-rc.1](https://github.com/chartjs/chartjs-plugin-datalabels/releases/tag/v2.0.0-rc.1). 

The ESM build is now correctly:
- pushed to the [tag](https://github.com/chartjs/chartjs-plugin-datalabels/tree/v2.0.0-rc.1/dist)
- attached to the [GH release](https://github.com/chartjs/chartjs-plugin-datalabels/releases/download/v2.0.0-rc.1/chartjs-plugin-datalabels.esm.js) 
- published to [npm](https://www.npmjs.com/package/chartjs-plugin-datalabels/v/2.0.0-rc.1) 
- available on [jsdelivr](https://www.jsdelivr.com/package/npm/chartjs-plugin-datalabels?version=2.0.0-rc.1&path=dist)

**Comment by hsablonniere** [comment]
You are awesome, thanks very much Simon 😍👍👏
