### ISSUE TITLE
getPositioner fails to properly test element class once module is transpiled 

### ISSUE THREAD

**Issue by gterras** [chartjs/chartjs-plugin-datalabels#251]
_chart.js: 3.3.1
chartjs-plugin-datalabels: 2.0.0-rc.1_

Hi and thanks for your plugin, 

I noticed that `getPositioner` cannot correctly detect the element type once code is transpiled (possibly related to https://github.com/chartjs/chartjs-plugin-datalabels/issues/185 ?). 

```html

// HTML 
<script src="https://cdn.jsdelivr.net/npm/chart.js/dist/chart.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.0.0-rc.1"></script>
<script>
Chart.register(ChartDataLabels);

const config = {
type: 'bar'
...
}

// chartjs-plugin-datalabels.js 
function getPositioner(el) {
  if (el instanceof ArcElement) {
    return positioners.arc;
  }
  if (el instanceof PointElement) {
    return positioners.point;
  }
  if (el instanceof BarElement) {
    // Will fall here
    return positioners.bar;
  }
  return positioners.fallback; 
}
</script>
```
```js
// ESM 
import ChartJS from 'chart.js/auto/auto.js'
import ChartDataLabels from 'chartjs-plugin-datalabels/dist/chartjs-plugin-datalabels.js'
ChartJS.register(ChartDataLabels)

const config = {
type: 'bar'
...
}

// chartjs-plugin-datalabels.js 
function getPositioner(el) {
  if (el instanceof chart_js.ArcElement) {
    return positioners.arc;
  }
  if (el instanceof chart_js.PointElement) {
    return positioners.point;
  }
  if (el instanceof chart_js.BarElement) {
    return positioners.bar;
  }
  // Will fall here
  return positioners.fallback; 
}

```

The same chart config works fine from a standalone HTML file but not in say a SvelteKit setup (doesn't seem Svelte/Vite related, could also be the case with Babel transpilation) . Everything else works fine. Could this fall into the caveats described here https://stackoverflow.com/questions/332422/get-the-name-of-an-objects-type ? 

It's hard to provide a reproducible sample since it _will_ work fine on say Codepen but I can provide a sveltekit repo if useful. 

Thanks

**Comment by gterras** [comment]
Something like 

```js
function getPositioner(el) {
  if (el.constructor.id === chart_js.ArcElement.id) {
    return positioners.arc;
  }
  if (el.constructor.id === chart_js.PointElement.id) {
    return positioners.point;
  }
  if (el.constructor.id === chart_js.BarElement.id) {
    return positioners.bar;
  }
  return positioners.fallback;
}
```

do work in both case by the way, I have no idea if it's a good idea to do so though.

**Comment by simonbrunel** [comment]
Thank you @gterras for testing the v2 pre-release. I initially thought to use the id but it's different from `instanceof` because it will not detect derived classes (e.g. `class CustomBarElement extends BarElement`). We could imagine to use `Element.id` as fallback to support such scenario but first I would like to investigate what are the other options.

Can you please build a simple repo that reproduces this issue?

**Comment by gterras** [comment]
Hi,

Find the repro here : 
https://github.com/gterras/repro-chartjs-plugin-datalabels-251

It's a base [sveltekit app](https://kit.svelte.dev/doc) with a chart.js component added in `/src/routes`. The chart config is taken from chart.js homepage. 

```
npm i
npm run dev
```

You should see the label positioning at the top (after fallback positioner processing). In dev env the file gets added to npm cache so it isn't convenient for debugging. You can 

`npm run build` to get a build in `/build` (sveltekit `adapter-static` is used so you get a browser ready build, you can use `adapter-node` for a SSR build). 

then `npm run preview` to see the build live. 

Thanks !

**Comment by simonbrunel** [comment]
Hi @gterras, thank you for the repo! The problem with your setup is that you import [`chart.js/auto/auto.js`](https://github.com/gterras/repro-chartjs-plugin-datalabels-251/blob/master/src/routes/_ChartJs.svelte#L4) which is the **UMD** build while you import the [chartjs-plugin-datalabels **ESM** build](https://github.com/gterras/repro-chartjs-plugin-datalabels-251/blob/master/src/routes/_ChartJs.svelte#L7). This can't work because the `Chart` (and so elements) you import is different from the `Chart` that the plugin imports.

Instead, you should import `chart.js/auto` which will [use the ESM build](https://github.com/chartjs/Chart.js/blob/master/auto/package.json#L6):

 ```js

**Comment by gterras** [comment]
Hi @simonbrunel thanks for your anwser it's working flawlessly now, sorry for the noise. :+1:
