### ISSUE TITLE
Display values only under conditions

### ISSUE THREAD

**Issue by paglop** [chartjs/chartjs-plugin-datalabels#45]
Hi,

I have the following values : [ "2", "10", "50", "120" ] 
And in my config : 
datalabels: {
   ...
    display: function(context) {
            return context.dataset.data[context.dataIndex] > 10;
    },
}"

Is there a solution to display the value only if it is higher than 10% of the max value ?
   ...
            return context.dataset.data[context.dataIndex] > (maxval * 10 / 100);
   ...

Result : only "50" and "120" are displayed

Thanks a lot,

**Comment by simonbrunel** [comment]
Looks like the correct approach, though *you* need to compute `maxval` since this is out of the scope of this plugin. You can certainly inspire yourself from [this answer](/chartjs/chartjs-plugin-datalabels/issues/16#issuecomment-348333846) (see this [jsfiddle](https://jsfiddle.net/simonbrunel/pqf03gt7/) I just wrote).

GitHub issues are reserved for bugs and feature requests, you should ask this kind of question/support requests on [StackOverflow](https://stackoverflow.com/questions/tagged/chart.js) instead.

**Comment by paglop** [comment]
Forgive me for asking my question here, I will use StackOverflow from now on.
Thank you very much for your answer, I should be able to draw inspiration from it.

**Comment by simonbrunel** [comment]
> Forgive me for asking my question here ...

No worries 😄 It helps maintainers to focus on bugs and features instead of spending too much time providing support while you could get valuable feedback faster from the rest of the community such as StackOverflow.

> ... I should be able to draw inspiration from it.

I feel that this [jsfiddle](https://jsfiddle.net/simonbrunel/pqf03gt7/) is exactly what you are looking for.

**Comment by paglop** [comment]
Thanks a lot, it works perfectly.
