### ISSUE TITLE
Editing options for data labels when using react-chartjs-2

### ISSUE THREAD

**Issue by glorenzen93** [chartjs/chartjs-plugin-datalabels#56]
Does anybody know how to get the options to work when using data labels with react-chartjs-2? Is it just on the options prop for the chart? I'm trying to have the chart only render a label if the bar has a value, right now it renders a label of 0. I'm also trying to adjust the padding since some of the labels go below the x axis.

**Comment by simonbrunel** [comment]
This tracker is reserved for general bug reports or feature requests and since I'm not familiar with `react` (and thus `react-chartjs`), it may be better to directly ask on [react-chartjs-2](https://github.com/jerairrest/react-chartjs-2) or, even better, [StackOverflow](https://stackoverflow.com/questions/tagged/chart.js) (actually, [this answer](https://stackoverflow.com/a/46471436) could help).

To hide labels without values, you can use scriptable options:

```javascript
plugins: {
  datalabels: {
    display: function(ctx) {
      return !!ctx.dataset.data[ctx.dataIndex];
    }
  }
}
```

**Comment by simonbrunel** [comment]
Closing as inactive.
