### ISSUE TITLE
Can I use this on my node.js app, combination with chartjs-node?

### ISSUE THREAD

**Issue by ryanxetm** [chartjs/chartjs-plugin-datalabels#83]

**Comment by simonbrunel** [comment]
I *think* it should work, did you try anything? You should ask this question directly in the [chartjs-node repository](https://github.com/vmpowerio/chartjs-node) or better on [StackOverflow](https://stackoverflow.com/questions/tagged/chart.js). I'm closing this issue since it's neither a bug report or a feature request but feel free to follow up on this ticket with related links.
