### ISSUE TITLE
'dist' should be removed from .gitignore 

### ISSUE THREAD

**Issue by rajkumar-osm** [chartjs/chartjs-plugin-datalabels#96]
When I do  `bower install chartjs-plugin-datalabels --save` script files will go under /dist.

If we want to push the lib directory to git, dist directory is being ignored as .gitignore is having 'dist' entry.

**Comment by simonbrunel** [comment]
@rajkumar-osm the `/dist` folder should definitely not be pushed in **our** repository because it contains generated files that we don't want in our branches. I'm not sure why you need to check-in these files in **your** repository (instead of doing another `bower install`) but it's up to you to force a `git add` (at least the first one):

```
git add -f /path/to/chartjs/dist/*.js
```

We are actually doing the same when [releasing a new version](/chartjs/chartjs-plugin-datalabels/blob/master/scripts/release.sh#L24).
